Project:
  name : .
  url_dataset : https://api.fda.gov/download.json
  chunk_size : 2500
  file_name_data_parquet : drugs_data.parquet

OpenFDA:
  - active_ingredient
  - adverse_reactions
  - brand_name
  - carcinogenesis_and_mutagenesis_and_impairment_of_fertility
  - clinical_pharmacology_table
  - clinical_studies_table
  - contraindications
  - description
  - dosage_and_administration
  - effective_time
  - general_precautions
  - generic_name
  - geriatric_use
  - id
  - inactive_ingredient
  - indications_and_usage
  - last_updated
  - manufacturer_name
  - nursing_mothers
  - overdosage
  - package_label_principal_display_panel
  - pharmacogenomics_table
  - precautions
  - pregnancy
  - pregnancy_or_breast_feeding
  - product_type
  - storage_and_handling
  - substance_name
  - use_in_specific_populations
  - warnings
  - when_using

OpenSearch:
  service : aoss
  host : "{{env('hostname')}}"
  port : 443
  use_ssl : True
  verify_certs : True
  pool_maxsize : 20
  timeout : 300

  Collection : 
    name : digital-drugs
    description : Colección para almacenar información de un vademecum digital
    type : SEARCH
    index : drugs-index
    

  DataAccessPolicy : 
    name: "{{OpenSearch.Collection.name}}-policy"
    description: Data access policy for {{OpenSearch.Collection.name}} collections
    policy:
      - Rules:
          - Resource:
              - index/{{OpenSearch.Collection.name}}/*
            Permission:
              - aoss:CreateIndex
              - aoss:DeleteIndex
              - aoss:UpdateIndex
              - aoss:DescribeIndex
              - aoss:ReadDocument
              - aoss:WriteDocument
            ResourceType: index
          - Resource:
              - collection/{{OpenSearch.Collection.name}}
            Permission:
              - aoss:CreateCollectionItems
            ResourceType: collection
        Principal:
          - arn:aws:iam::{{env('aws_account_id')}}:user/{{env('aws_user_name')}}
    type : data

  EncryptionPolicy :
    name: "{{OpenSearch.Collection.name}}-policy"
    description: Encryption policy for {{OpenSearch.Collection.name}} collections
    policy:
      Rules:
        - ResourceType: collection
          Resource:
            - collection/{{OpenSearch.Collection.name}}
      AWSOwnedKey: true
    type: encryption

  NetworkPolicy : 
    name: "{{OpenSearch.Collection.name}}-policy"
    description: NetworkPolicy for {{OpenSearch.Collection.name}} collections
    policy :
      - Description: ""
        Rules:
          - ResourceType: dashboard
            Resource:
              - collection/{{OpenSearch.Collection.name}}
          - ResourceType: collection
            Resource:
              - collection/{{OpenSearch.Collection.name}}
        AllowFromPublic: true
    type: network
