Project:
  name : .
  url_dataset : https://api.fda.gov/download.json
  chunk_size : 2500
  file_name_data_parquet : drugs_data.parquet

OpenFDA:
  - abuse
  - active_ingredient
  - adverse_reactions
  - alarms
  - ask_doctor_or_pharmacist
  - ask_doctor_table
  - brand_name
  - carcinogenesis_and_mutagenesis_and_impairment_of_fertility
  - clinical_pharmacology_table
  - clinical_studies_table
  - components_table
  - contraindications
  - controlled_substance
  - dependence
  - description
  - do_not_use_table
  - dosage_and_administration
  - drug_abuse_and_dependence
  - drug_and_or_laboratory_test_interactions_table
  - drug_interactions_table
  - effective_time
  - general_precautions
  - generic_name
  - geriatric_use
  - how_supplied_table
  - id
  - inactive_ingredient
  - indications_and_usage
  - information_for_patients_table
  - instructions_for_use
  - labor_and_delivery
  - laboratory_tests
  - last_updated
  - manufacturer_name
  - mechanism_of_action_table
  - microbiology_table
  - nonteratogenic_effects
  - nursing_mothers
  - overdosage
  - package_label_principal_display_panel
  - patient_medication_information
  - pediatric_use_table
  - pharmacodynamics_table
  - pharmacogenomics_table
  - pharmacokinetics_table
  - precautions
  - pregnancy
  - pregnancy_or_breast_feeding
  - product_type
  - purpose_table
  - questions_table
  - recent_major_changes
  - risks
  - spl_medguide
  - spl_patient_package_insert
  - statement_of_identity
  - stop_use_table
  - storage_and_handling
  - substance_name
  - summary_of_safety_and_effectiveness
  - teratogenic_effects
  - use_in_specific_populations
  - user_safety_warnings
  - warnings
  - warnings_and_cautions_table
  - when_using

OpenSearch:
  service : aoss
  host : "{{env('hostname')}}"
  port : 443
  use_ssl : True
  verify_certs : True
  pool_maxsize : 20
  timeout : 300

  Collection : 
    name : digital-drugs
    description : Colección para almacenar información de un vademecum digital
    type : SEARCH
    index : drugs-index
    

  DataAccessPolicy : 
    name: "{{OpenSearch.Collection.name}}-policy"
    description: Data access policy for {{OpenSearch.Collection.name}} collections
    policy:
      - Rules:
          - Resource:
              - index/{{OpenSearch.Collection.name}}/*
            Permission:
              - aoss:CreateIndex
              - aoss:DeleteIndex
              - aoss:UpdateIndex
              - aoss:DescribeIndex
              - aoss:ReadDocument
              - aoss:WriteDocument
            ResourceType: index
          - Resource:
              - collection/{{OpenSearch.Collection.name}}
            Permission:
              - aoss:CreateCollectionItems
            ResourceType: collection
        Principal:
          - arn:aws:iam::{{env('aws_account_id')}}:user/{{env('aws_user_name')}}
    type : data

  EncryptionPolicy :
    name: "{{OpenSearch.Collection.name}}-policy"
    description: Encryption policy for {{OpenSearch.Collection.name}} collections
    policy:
      Rules:
        - ResourceType: collection
          Resource:
            - collection/{{OpenSearch.Collection.name}}
      AWSOwnedKey: true
    type: encryption

  NetworkPolicy : 
    name: "{{OpenSearch.Collection.name}}-policy"
    description: NetworkPolicy for {{OpenSearch.Collection.name}} collections
    policy :
      - Description: ""
        Rules:
          - ResourceType: dashboard
            Resource:
              - collection/{{OpenSearch.Collection.name}}
          - ResourceType: collection
            Resource:
              - collection/{{OpenSearch.Collection.name}}
        AllowFromPublic: true
    type: network
